AWSTemplateFormatVersion: 2010-09-09

Description: |
  Kittens Carousel is a static website application deployed on AWS Simple Storage Service (S3), served through 
  Cloudfront and Route 53 using AWS Cloudformation Service.

# Parameters:
  
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kittens.ikjoshdevopsjourney.click
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags: 
        - Key: Name
          Value: joshua-kittens-bucket
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html


  MyS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket # Required
      PolicyDocument:  # Required
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - /*
            Principal: '*'
            Sid: PublicReadGetObject

  MyCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref MyS3Bucket
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          ForwardedValues: 
              Cookies: 
                Forward: none
              QueryString: true
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
       # HttpVersion: "String"

        Origins:
          - CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName: kittens.clarusway.us.s3-website.us-east-1.amazonaws.com
            Id: KittensOrigin
        # ViewerCertificate:

  MyDNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z05137422XNV2ULWYDSYO
      RecordSets: 
        - AliasTarget: 
            DNSName: !GetAtt MyCloudfrontDistribution.DomainName 
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref MyS3Bucket
          Type: A
        

Outputs:
  MyBucketWebsiteURL:
    Description: The URL of the static webpage.
    Value: !GetAtt MyS3Bucket.WebsiteURL

  FullyQualifiedDomainName:
    Description: FQDN
    Value:  !Ref MyS3Bucket
